/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.pingpong.stockx;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        draw();
    }

    public static void draw() {
        System.out.println(
        "\t" + " _    _" + "\n" +
        "\t" + "(_\\__/(,_" + "\n" +
        "\t" + "| \\ `_////-._" + "\n" +
        "\t" + "J_/___\"=> __/`\\" + "\n" +
        "\t" + "|=====;__/___./" + "\n" +
        "\t" + "\'-\'-\'-\"\"\"\"\"\"\"`" );
    }
}
